version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: nextjs_db
    environment:
      POSTGRES_USER: nextjs_db
      POSTGRES_PASSWORD: nextjs_db
      POSTGRES_DB: nextjs_db

    command: postgres -c 'max_connections=1000'
    ports:
      - "5433:5432"
    volumes:
      - nextjs_db:/var/lib/postgresql/data

volumes:
  nextjs_db:
