import { Container } from "@/components/ui/container";
import { useGetUserDataServer } from "@/hooks/get-user/useGetUserServer";
import clsx from "clsx";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import Navbar from "../components/layout/Navbar";
import "./globals.css";
const Providers = dynamic(() => import("@/providers/Providers"), {
	ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const Session = await useGetUserDataServer();

	return (
		<html lang="en">
			<body className={clsx(inter.className)}>
				<Providers session={Session}>
					<Navbar />
					<Container>
						<main>{children}</main>
					</Container>
				</Providers>
			</body>
		</html>
	);
}
